FROM rust:1.83.0 AS builder

WORKDIR /app

ENV AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu
ENV AARCH64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR=/usr/include/aarch64-linux-gnu/openssl

RUN dpkg --add-architecture arm64 &&  \
    apt-get update && \
    apt-get install -y \
            build-essential  \
            pkg-config git-all  \
            protobuf-compiler \
            gcc-aarch64-linux-gnu  \
            g++-aarch64-linux-gnu \
            libssl-dev:arm64 && \
    rm -rf /var/lib/apt/lists/* && \
    git clone https://github.com/sgs-fork/network-api.git .

WORKDIR /app/clients/cli

RUN rustup target add aarch64-unknown-linux-gnu && \
    cargo build --release --bin prover --target aarch64-unknown-linux-gnu

FROM debian:bullseye-slim

WORKDIR /app

COPY --from=builder /app/clients/cli/target/aarch64-unknown-linux-gnu/release/prover /app/prover

CMD ["sh", "-c", "exec /app/prover -- beta.orchestrator.nexus.xyz"]