FROM rust:1.83.0

WORKDIR /app

ENV X86_64_UNKNOWN_LINUX_GNU_OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu
ENV X86_64_UNKNOWN_LINUX_GNU_OPENSSL_INCLUDE_DIR=/usr/include/x86_64-linux-gnu/openssl

RUN apt-get update && \
    apt-get install -y \
            build-essential  \
            pkg-config  \
            git-all  \
            protobuf-compiler \
            libssl-dev && \
    rm -rf /var/lib/apt/lists/* && \
    git clone https://github.com/sgs-fork/network-api.git .

WORKDIR /app/clients/cli

RUN rustup target add x86_64-unknown-linux-gnu && \
    cargo build --release --bin prover --target x86_64-unknown-linux-gnu
CMD ["cargo", "run", "--release", "--bin", "prover", "--", "beta.orchestrator.nexus.xyz"]